### ISSUE TITLE
PlainText Serializer incorrectly unmarshalls deeply nested clusters/arrays that contain multiple ] or } characters

### ISSUE THREAD

**Issue by IlyaVino** [LabVIEW-Open-Source/Serializer#10]
This is a bug I referenced at the end of https://github.com/LabVIEW-Open-Source/Serializer/issues/5

This bug exists for deeply nested clusters and arrays such as:
![deeply nested cluster array](https://user-images.githubusercontent.com/76701408/150222346-a0196639-6e58-4992-b68f-84329392552a.PNG)

which generate plain text strings:

`[{"asdf",[{[1.0,2.0],"asdf"},{[3.0,4.0],"ghjk"}]},{"ghjk",[{[1.0,2.0],"asdf"},{[3.0,4.0],"ghjk"}]}]`
`{[{[1.0,2.0],"asdf"},{[3.0,4.0],"ghjk"}]}`
 
Whenever PlainTextToVariant encounters a nested ] or }, it may switch the data type it is parsing from "cluster" or "array" to "unknown". This should only happen for the outermost ] or } so that the contents can be parsed recursively. 

For example, the second cluster's contents are initially parsed under the "array" flag based on the second [ character but when encountering the first ] character after 2.0, the parsing incorrectly switches to "unknown". Instead, the flag should only be changed when encountering the outermost ] character at the end so that the full contents of the array inside the [ ... ] is parsed recursively.

My suggested fix is to add a counter that keeps track of the bracket depth. For example:
![bracket counter inside plainTextToVariant](https://user-images.githubusercontent.com/76701408/150222420-7942875e-bc9f-4dda-b40c-d8d8550f348a.PNG)

This counter needs to be added for all cases involved in parsing nested data types, i.e. under the cluster ("{" .. "{\~") and array ("[" .. "[\~") case. Any subcase that has "[" or "{" needs an increment and any subcase that has "]" or "}" needs a decrement and check to see if the counter is at zero.

I'll clean up my changes to the vi a bit and compile some tests shortly.

**Comment by IlyaVino** [comment]
Here with compiled tests, including a test for this issue, issue #5, and the tests that shipped with v1.2.0
[Test Serializer.Text.zip](https://github.com/LabVIEW-Open-Source/Serializer/files/7901138/Test.Serializer.Text.zip)

@francois-normandin, I've decided to upload my changes to the VI here since there may still be issues with these deeply nested data types and the data manipulation library. Let me know if you prefer a pull request instead.
[PlainTextToVariant (Standard).zip](https://github.com/LabVIEW-Open-Source/Serializer/files/7901143/PlainTextToVariant.Standard.zip)

**Comment by francois-normandin** [comment]
Thanks @IlyaVino 
This should do it indeed. I usually implement those in a recursive way but the shift register should work great while I develop a real "lexer" class to add to the serializer (but this will probably be at a later date... )

**Comment by francois-normandin** [comment]
Marvelous, @IlyaVino 
I`ve added your unit tests along the few extra one for Issues 7,8,9 and now the full test suite passes.

**Comment by francois-normandin** [comment]
Released 1.2.1 (will be sent to vipm.io shortly)

https://github.com/LabVIEW-Open-Source/Serializer/releases/tag/1.2.1

**Comment by IlyaVino** [comment]
Great! Thanks again for all the help with these issues.
